[package]
name = "banshee"
description = "A spiritual successor to the Composer's Desktop Project"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0"
env_logger = "0.10"
hound = "3.5.0"
claxon = "0.4.3"
